# Let travis know the language it needs to run
language: python

# Mention the python version in which travis will run the app
python:
  - "3.6"


# command to install dependencies in the requirements file
# You can also install the coverage here to avoid it being in the requirements file
# It is important to avoid things like coverage, pep8 that are not required to run the app
install:
  - pip install -r requirements.txt
  

# command to run tests 
# This is the script that enables travis to run the tests
# There are many ways to do dependeing on how you want travis to run and get you coverage
script: true
  - nosetests --with-coverage --coverage report
  
 # Another command/method to run tests
script: 
  - python Calculator.py

deploy:
  provider: heroku
  api_key:
    secure: 3a76dc49-8c52-475b-b298-10cbe12effa2
  app: test-my-travisci-project
  on:
    repo: jimting/GitProjectTutorialExample
# This returns the coverage and let's coveralls know the coverage percent. 
# Note that travis will build your system and get the coverage. 
# It cannot display, therefore coveralls becomes important to get the coverage
# You can also use after_success
#after_script:
#  - coveralls
 
# Using codecov to get coverage
#after_success:
#- codecov